name: Build Project

on:
  push:
    branches: [master, develop]
    tags-ignore:
      - "*"
  pull_request:
    branches: [master, develop]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          profile: minimal
      - uses: Swatinem/rust-cache@v1
        with:
          key: ${{ matrix.os }}-deps-${{ hashFiles('Cargo.lock') }}
      - name: Build projects with all features
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features --locked
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}
          path: |
            target/release/pkg-upd
            target/release/pkg-upd.exe

  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Install-latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          profile: minimal
      - uses: Swatinem/rust-cache@v1
        with:
          key: ${{ matrix.os }}-deps-${{ hashFiles('Cargo.lock') }}
      - name: Test projects with all features
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --all-features --locked
